### ISSUE TITLE
Twig\Error\LoaderError Unable to find template "sorrt.twig"

### ISSUE THREAD

**Issue by j-nordell** [treehouse-apprenticeship/tap-team-project-php-mailchimp-2#12]
When sorting by tags we get the error Twig\Error\LoaderError Unable to find template "sorrt.twig"

**Comment by mdbyrd1920** [comment]
There is a **typo** in the routes.php file on line 213. It should be "sort.twig" instead of "sorrt.twig".

**Comment by bviengineer** [comment]
Resolved by PR #29
